### ISSUE TITLE
Worldserver Crash (Access Violation)

### ISSUE THREAD

**Issue by ManGuyNY** [ZhengPeiRu21/mod-playerbots#126]
Worldserver.exe crashed with this error:

Unhandled exception at 0x00007FF6A67E9677 in worldserver.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

![image](https://user-images.githubusercontent.com/115581060/196317201-77f3fac9-0f58-4800-a167-00c0b40fe28a.png)

![image](https://user-images.githubusercontent.com/115581060/196317266-3c2021a1-40c5-43a2-b9df-99634c6af65a.png)

I had left the server idling. No human players were on at the time.

**Comment by corker22** [comment]
im not sure if this will help you but i was able to fix mine # https://github.com/azerothcore/azerothcore-wotlk/pull/13465
i had do do manual changes not a simply copy and paste of the files, that breaks changes made from playerbots branch. also haven't done any coding since high school(20 years ago) so i hope this makes sense

**Comment by ManGuyNY** [comment]
Does this mean that this crash was not caused by the playerbots? I have another realm that uses Trickerer's NPCbot fork of Azerothcore and it has never crashed on me while idling. I'm a complete novice at coding myself 😭 I wish I could contribute more than just bug reports.

**Comment by corker22** [comment]
im using playerbots fork haven't tried tricksters

**Comment by ZhengPeiRu21** [comment]
Thank you for submitting this issue. I apologize it has taken me so long to respond! I believe that the underlying issue causing this crash has been fixed. Please re-open this issue if you still see this occur!
