### ISSUE TITLE
ninth fail

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#13]
![Screenshot_2022-03-25-20-07-37-307_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160213292-42cc6d9f-b3a5-4c8b-ba48-5916331334b0.jpg)
![Screenshot_2022-03-25-20-07-53-250_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160213299-9506dcd5-77a1-4114-becb-c42816344d17.jpg)

**Comment by htc16** [comment]
![image](https://user-images.githubusercontent.com/58153179/160218911-ba779707-e1e1-4a5e-a5ba-2113f18f4cd1.png)
![image](https://user-images.githubusercontent.com/58153179/160218920-5a9ae00a-21e6-41e5-8b38-c9cc0f75c2d6.png)

**Comment by ZhengPeiRu21** [comment]
The first crash when applying random item enchantment should be fix in https://github.com/ZhengPeiRu21/mod-playerbots/commit/6d56c5c5c36937b78e2d14af7ea2d4c9d055a3d6. Unfortunately the stack trace log for the second crash is very hard to debug because it is all during map update code - do you have a longer log that gives a more complete trace for this crash?

**Comment by htc16** [comment]
I had Zheng, you can close this problem, and if he come back again I reopen.
