### ISSUE TITLE
编译到最后报下面的错

### ISSUE THREAD

**Issue by SliderBeen** [ZhengPeiRu21/mod-playerbots#136]
azerothcore用你的分支的Playerbot，用azerothcore官方步骤编译
[100%] Linking CXX executable worldserver
clang: error: unable to execute command: Killed
clang: error: linker command failed due to signal (use -v to see invocation)
make[2]: *** [src/server/apps/CMakeFiles/worldserver.dir/build.make:177: src/server/apps/worldserver] Error 254
make[1]: *** [CMakeFiles/Makefile2:988: src/server/apps/CMakeFiles/worldserver.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by runto2006** [comment]
azerothcore用你的分支的Playerbot，用azerothcore官方步骤编译
[ 13%] Building CXX object modules/CMakeFiles/modules.dir/mod-playerbots-AzerothCore/src/ChatFilter.cpp.o
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/ChatFilter.cpp:7:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/Playerbots.h:8:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/strategy/AiObjectContext.h:9:
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:83:20: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
            return std::move(keys);
                   ^
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:83:20: note: remove std::move call here
            return std::move(keys);
                   ^~~~~~~~~~    ~
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:145:20: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
            return std::move(keys);
                   ^
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:145:20: note: remove std::move call here
            return std::move(keys);
                   ^~~~~~~~~~    ~
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:217:20: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
            return std::move(std::set<std::string>());
                   ^
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:217:20: note: remove std::move call here
            return std::move(std::set<std::string>());
                   ^~~~~~~~~~                       ~
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:231:20: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
            return std::move(result);
                   ^
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:231:20: note: remove std::move call here
            return std::move(result);
                   ^~~~~~~~~~      ~
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:245:20: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
            return std::move(result);
                   ^
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/NamedObjectContext.h:245:20: note: remove std::move call here
            return std::move(result);
                   ^~~~~~~~~~      ~
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/ChatFilter.cpp:7:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/Playerbots.h:11:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/PlayerbotAI.h:17:
/root/acore/modules/mod-playerbots-AzerothCore/src/PlayerbotTextMgr.h:27:65: warning: field 'm_guid' will be initialized after field 'm_type' [-Wreorder-ctor]
    ChatReplyData(uint32 guid, uint32 type, std::string chat) : m_guid(guid), m_type(type), m_chat(chat) {}
                                                                ^
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/ChatFilter.cpp:7:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/Playerbots.h:15:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/strategy/values/SharedValueContext.h:11:
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/strategy/values/QuestValues.h:9:
/root/acore/modules/mod-playerbots-AzerothCore/src/TravelMgr.h:85:9: warning: definition of implicit copy assignment operator for 'WorldPosition' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy]
        WorldPosition(WorldPosition const& pos) : WorldLocation(pos), visitors(pos.visitors) { }
        ^
/root/acore/modules/mod-playerbots-AzerothCore/src/TravelMgr.h:371:117: note: in implicit copy assignment operator for 'WorldPosition' first required here
        FindPointCreatureData(WorldPosition point1 = WorldPosition(), float radius1 = 0, uint32 entry1 = 0) { point = point1; radius = radius1; entry = entry1; }
                                                                                                                    ^
In file included from /root/acore/modules/mod-playerbots-AzerothCore/src/ChatFilter.cpp:8:
/root/acore/modules/mod-playerbots-AzerothCore/src/strategy/values/RtiTargetValue.h:16:117: warning: field 'type' will be initialized after base 'TargetValue' [-Wreorder-ctor]
        RtiTargetValue(PlayerbotAI* botAI, std::string const type = "rti", std::string const name = "rti target") : type(type), TargetValue(botAI, name) { }
                                                                                                                    ^
/root/acore/modules/mod-playerbots-AzerothCore/src/ChatFilter.cpp:166:47: fatal error: no member named 'GetTargetIcon' in 'Group'
                ObjectGuid rtiTarget = group->GetTargetIcon(RtiTargetValue::GetRtiIndex(rti.substr(1)));
                                       ~~~~~  ^
8 warnings and 1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:89: modules/CMakeFiles/modules.dir/mod-playerbots-AzerothCore/src/ChatFilter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1474: modules/CMakeFiles/modules.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by justaswell** [comment]
delete the "-AzerothCore", rename the folder name to "mod-playerbots".

**Comment by SliderBeen** [comment]
内存从4G扩到8G，重新编译，不报错，这应该是内存问题
