### ISSUE TITLE
[1146] Table 'acore_world.charsections_dbc' doesn't exist

### ISSUE THREAD

**Issue by peckwood** [ZhengPeiRu21/mod-playerbots#167]
When starting world server, it reports 
```
[1146] Table 'acore_world.charsections_dbc' doesn't exist
Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.
```
However, I cannot find table charsections_dbc in any of the sql files inside sql/updates.

I built the server from https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/Playerbot

**Comment by Barry-Beez** [comment]
Hey, I had this issue too but it's an easy fix: just build with mod-playerbots in the module folder of the source AzerothCore folder.
FIY, the file is located at the mod-playerbots/sql/world folder.
> Your database structure is not up to date. Please make sure you've executed all queries in the sql/updates folders.

What you see on the server command prompt is because it has no way to know the sql file you want to update with is in a module, so it asks you to check the expected directory for an sql update, eg: sql/updates.

When you have an issue like this one, just do a search on all your source files, this is the way I solved many issues I had: once you find what you're looking for they're easy to fix!
Hopefully this answer will help you and others with this issue, enjoy.

Thanks a lot ZhengPeiRu21 for this module, you're the man!
I'll try to learn as much as I can and hopefully contribute one day.

**Comment by peckwood** [comment]
I copied mod-playerbots inside the module folder and built, now the bots are working now! Thanks Barry-Beez!
