### ISSUE TITLE
Bot Exit Crash

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-playerbots#21]
Too much crash for this reason
![Screenshot_2022-03-29-14-20-20-520_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160670398-1c618aa4-7df3-407a-80b3-28a4b7f7197a.jpg)
![Screenshot_2022-03-29-14-20-29-955_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160670405-624019af-4549-498e-84e6-612248179b35.jpg)
![Screenshot_2022-03-29-14-20-38-110_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160670410-4d913194-4f14-48c4-a58e-3ac47d503c18.jpg)

**Comment by ZhengPeiRu21** [comment]
It seems the crash is occur because a bot's map pointer has been reset but the bot is still present in the world. This may be due to failed logout. Because this is during threaded map update, it is difficult to find the origin of the this bug. Can you post a complete server log with DEBUG log level when this crash occurs? I think that will be the only way to find the source.

**Comment by htc16** [comment]
do you need the log that the console automatically generates?  that one alone, will it help?  Or would it be even more specific?

**Comment by htc16** [comment]
![Screenshot_2022-03-30-07-19-55-996_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160809724-07d6fe19-636b-455b-a5cf-a9c2fb7e798a.jpg)

**Comment by htc16** [comment]
![Screenshot_2022-03-30-10-26-28-358_com server auditor ssh client](https://user-images.githubusercontent.com/58153179/160845597-ec14d19a-09ef-4097-b3fc-12df4cd43aa1.jpg)
