### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by BRNKR** [ZhengPeiRu21/mod-playerbots#92]
Hey @ZhengPeiRu21 ,

how can I contribute ? Just by PR? Do you use any discussion platform like discord ? is there any TODO list? Did you already ported all the code from celguar into this repo ? celguar is quiet heavily fixing things. how do you stay updated?
Keep going. 
best regards

**Comment by Deathman182** [comment]
Would like to know the answer on that as well 😅

**Comment by ZhengPeiRu21** [comment]
Hello. Sorry for the slow responding! Thank you for willingness to support. Because of code differences between AzerothCore and Mangos, all of Celguar's changes need to be manually adjusted and ported. This is why many of my PRs are have the exact title of Celguar's - it is help me track how far I have ported the code. We are currently a couple month of update behind but slowly are catch up.

In addition to just port the changes, there are also many bugs unique to the AC bots that are still need to be resolve. The biggest issue right now is that somehow, action strings are somehow getting interpreted as formation strings, which is causing most of the "stupid" behavior of the bots. This issue so far has been difficult to debug, but I am working to solve it as a high priority issue, because it will resolve many behaviors.

Any PRs are very welcome! Issue reports are also helpful, especially with full crashlogs if there is a crash. I am activate on AzerothCore Discord; please feel free to reach me there.

**Comment by Dreathean** [comment]
@Squizzy911 Please close out this issue as this discussion has long been over. Thanks!
